"""Vedrakit: a small, dependency-light Python web framework.

The public API intentionally keeps the FastAPI-like decorators from the
original prototype while adding an application object for isolated tests and
multiple services.
"""

__version__ = "1.1.0"

from .core import (
    ACTIVE_REQUESTS,
    AdvancedMiniFlask,
    REQUEST_COUNT,
    REQUEST_LATENCY,
    App,
    BaseModel,
    Config,
    Database,
    Migration,
    Model,
    Param,
    ParamTypes,
    Path,
    Query,
    RedisManager,
    RequestHandler,
    Role,
    Security,
    TaskQueue,
    User,
    UserCreate,
    UserResponse,
    WebSocketManager,
    app,
    background_task,
    cache,
    configure_logging,
    delete,
    depends,
    exception_handler,
    generate_latest,
    get,
    graphql_schema,
    get_current_user,
    middleware,
    post,
    put,
    requires_role,
    route,
    run,
    run_grpc_server,
    run_metrics_server,
    run_websocket_server,
    routes,
    middlewares,
    exception_handlers,
    task_queues,
    websocket_handlers,
    graphql_schemas,
    websocket_endpoint,
)
from .codegen import generate_typescript_client, generate_typescript_client_file

__all__ = [
    "ACTIVE_REQUESTS",
    "AdvancedMiniFlask",
    "REQUEST_COUNT",
    "REQUEST_LATENCY",
    "App",
    "BaseModel",
    "Config",
    "Database",
    "Migration",
    "Model",
    "Param",
    "ParamTypes",
    "Path",
    "Query",
    "RedisManager",
    "RequestHandler",
    "Role",
    "Security",
    "TaskQueue",
    "User",
    "UserCreate",
    "UserResponse",
    "WebSocketManager",
    "app",
    "background_task",
    "cache",
    "configure_logging",
    "delete",
    "depends",
    "exception_handler",
    "generate_latest",
    "get",
    "graphql_schema",
    "get_current_user",
    "middleware",
    "post",
    "put",
    "requires_role",
    "route",
    "run",
    "run_grpc_server",
    "run_metrics_server",
    "run_websocket_server",
    "routes",
    "middlewares",
    "exception_handlers",
    "task_queues",
    "websocket_handlers",
    "graphql_schemas",
    "websocket_endpoint",
    "generate_typescript_client",
    "generate_typescript_client_file",
    "__version__",
]
